# This workflow is managed by gh actions-lock.

name: Send notification on new issue
on:
  issues:
    types: [opened]

permissions: {}

jobs:
  # tag the team from the variables on any new issues created in this repo
  tag-a-user:
    if: ${{ vars.SEND_NOTIFICATION == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps: 
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@v7.0.1

    - id: get-token
      name: Resolve the token to use
      uses: $/.github/actions/resolve-tokens
      with:
        target-server-url: ${{ vars.TARGET_SERVER_URL }}
        # this workflow only comments on an issue in the issues repository
        source-token-required: 'false'
        use-github-app: ${{ vars.USE_GITHUB_APP }}
        app-id: ${{ secrets.GH_AUTOMATION_ID }}
        private-key: ${{ secrets.GH_AUTOMATION_PRIVATE_KEY }}
        target-org: ${{ vars.TARGET_ORG || github.repository_owner }}
        target-permissions: |
          contents: read
          issues: write
        pat: ${{ secrets.PAT_GITHUB }}

    - uses: devops-actions/issue-comment-tag@v0.1.10
      name: Tag a user or team in an issue comment
      with: 
        issue: ${{ github.event.issue.number }}
        team: ${{ vars.NOTIFICATION_TEAM }}
        owner: ${{ github.repository_owner }}
        repo: ${{ github.repository }}
        GITHUB_TOKEN: ${{ steps.get-token.outputs.target-token }}
