# This workflow is managed by gh actions-lock.

name: PSScriptAnalyzer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '30 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  psscriptanalyzer:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: ./
          recurse: true
          output: results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4.37.3
        if: always()
        with:
          sarif_file: results.sarif
