# This workflow is managed by gh actions-lock.

name: Update the fork
on: 
  issues:
    types: [labeled]

permissions: {}

jobs:
  update-fork:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'update-fork'
    permissions:
      contents: write
      actions: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@v7.0.1

    - id: get-token
      name: Resolve the tokens to use
      uses: $/.github/actions/resolve-tokens
      with:
        target-server-url: ${{ vars.TARGET_SERVER_URL }}
        use-github-app: ${{ vars.USE_GITHUB_APP }}
        app-id: ${{ secrets.GH_AUTOMATION_ID }}
        private-key: ${{ secrets.GH_AUTOMATION_PRIVATE_KEY }}
        target-org: ${{ vars.TARGET_ORG || github.repository_owner }}
        pat: ${{ secrets.PAT_GITHUB }}
        use-public-github-app: ${{ vars.USE_PUBLIC_GITHUB_APP }}
        public-app-id: ${{ secrets.GH_PUBLIC_APP_ID }}
        public-private-key: ${{ secrets.GH_PUBLIC_APP_PRIVATE_KEY }}
        public-org: ${{ vars.PUBLIC_GITHUB_ORG }}
        public-pat: ${{ secrets.PAT_GITHUB_PUBLIC }}

    - env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
       echo "Found the issue that triggered this event with number [$ISSUE_NUMBER]"
       echo "Found the issue title [$ISSUE_TITLE]"

    - env:
        ORG_NAME: ${{ vars.TARGET_ORG || github.repository_owner }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_ID: ${{ github.event.issue.number }}
        ISSUES_REPOSITORY: ${{ github.repository }}
        TARGET_TOKEN: ${{ steps.get-token.outputs.target-token }}
        SOURCE_TOKEN: ${{ steps.get-token.outputs.source-token }}
        TARGET_SERVER_URL: ${{ steps.get-token.outputs.target-server-url }}
      run: |
       .\update-fork.ps1 -orgName $env:ORG_NAME -userName "xxx" -targetToken $env:TARGET_TOKEN -sourceToken $env:SOURCE_TOKEN -targetServerUrl $env:TARGET_SERVER_URL -issueTitle "$env:ISSUE_TITLE" -issueId $env:ISSUE_ID -issuesRepository $env:ISSUES_REPOSITORY
      shell: pwsh
